version: '3.8'

services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./nginx-data:/usr/share/nginx/html
    networks:
      - projetos
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.01'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

networks:
  projetos:
    external: true